### ISSUE TITLE
Release-0.5.0 Roadmap

### ISSUE THREAD

**Issue by Aireed** [NetEase/amoro#1333]
We will release the issue in 0.5.0

Feature Development
-----
- [x] https://github.com/NetEase/arctic/issues/261
- [x] https://github.com/NetEase/arctic/issues/1383
- [x] #5 
- [x] https://github.com/NetEase/arctic/issues/1476
- [x] https://github.com/NetEase/arctic/issues/1535
- [x] https://github.com/NetEase/arctic/issues/1537
- [x] https://github.com/NetEase/arctic/issues/1628
- [x] #1322   
- [x] #1339 

Improvement
-----
- [x] https://github.com/NetEase/arctic/issues/1372
- [x] https://github.com/NetEase/arctic/issues/1311
- [x] https://github.com/NetEase/arctic/issues/1349
- [x] https://github.com/NetEase/arctic/issues/1059
- [x] https://github.com/NetEase/arctic/issues/1350
- [x] https://github.com/NetEase/arctic/issues/1544

Bug Tracking
-----
- [x] https://github.com/NetEase/arctic/issues/1347
- [x] https://github.com/NetEase/arctic/issues/1346
- [x] https://github.com/NetEase/arctic/issues/1332
- [x] https://github.com/NetEase/arctic/issues/1330
- [x] https://github.com/NetEase/arctic/issues/488
- [x] https://github.com/NetEase/arctic/issues/1385
- [x] https://github.com/NetEase/arctic/issues/1397
- [x] #1751
- [x] #1653 
- [x] #1646

Document Improvement
-----
- [x] https://github.com/NetEase/arctic/issues/1340
- [x] #1510
