### ISSUE TITLE
[Feature]: Support killing the running optimizing process

### ISSUE THREAD

**Issue by archer2012** [NetEase/amoro#1862]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Due to some historical reasons, for some tables with serious fragmentation, it may require a lot of resources to enable self-o
ptimize for the first time, and even cannot be merged or  take a long time. We hope to kill or skip this optimize process

<img width="1887" alt="74978f2911a1e26c698fb1cfc419c18" src="https://github.com/NetEase/amoro/assets/3227239/2cdf5c0d-9fe3-435e-8c33-3049544d0ee2">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

- [x] #2299 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baiyangtx** [comment]
Thank you for suggesting this improvement. 'kill optimizing' is a relatively important operations and maintenance requirement. Currently, the preliminary plan is to implement this function in the standard operations and maintenance instructions.  You can follow it in this issue 

[](https://github.com/NetEase/amoro/issues/1357)

However, before that, should we provide other ways to solve such operations and maintenance problems? For example, providing a script to clean up optimizing processes and so on.  @zhoujinsong

**Comment by wangtaohz** [comment]
> However, before that, should we provide other ways to solve such operations and maintenance problems? For example, providing a script to clean up optimizing processes and so on. @zhoujinsong

From a product design perspective, I think providing a `Cancel` operation (maybe a button) for each optimizing process in Web UI is a practical way, that will provide convenience for optimizing recovery and retry.

**Comment by zhongqishang** [comment]
> * [[Feature]: Provide standard SQL management instructions and command-line tools #1357](https://github.com/NetEase/amoro/issues/1357)

That's cool.

But I prefer the `Cancel` button as @wangtaohz said, If just cancel the task, I believe it will be scheduled again to generate a new optimize task.
Maybe we can provided a button to enable/disable self-optimizing? 
After disable self-optimizing, cancel the currently executing optimizing task.

**Comment by tcodehuber** [comment]
> * [Feature]: Provide standard SQL management instructions and command-line tools #1357

This feature is valuable for external optimizers.  I have implemented this part of the code logic as @wangtaohz mentioned, can you assign a subtask to me for contribution.

**Comment by tcodehuber** [comment]
> * [Feature]: Provide standard SQL management instructions and command-line tools #1357

This feature is valuable for external optimizers.  I have implemented this part of the code logic as @wangtaohz mentioned, can you assign a subtask to me for contribution.

**Comment by wangtaohz** [comment]
> This feature is valuable for external optimizers. I have implemented this part of the code logic as @wangtaohz mentioned, can you assign a subtask to me for contribution.

👍 @tcodehuber You can create your own subtask and describe your approach, and I can assist in assigning the subtask to you.
