### ISSUE TITLE
[Improvement]: Critical vulnerabilities in the project dependencies need to be fixed

### ISSUE THREAD

**Issue by XBaith** [NetEase/amoro#2040]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

According to the OWASP Dependency-Check (https://owasp.org/www-project-dependency-check/), there are a number of vulnerabilities in the project dependencies, some of which are critical security issues that need to be fixed

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- [] #2038 
- [] #2039

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
