### ISSUE TITLE
[Improvement]: Add English documentation pages

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/amoro#765]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

I want to improve the English documentation pages.
https://arctic.netease.com/en/

### How should we improve?

Translate the Chinese documentation pages into English.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- [x] #766 
- [x] #767  
- [x] #768 
- [x] #769  
- [x] #770  
- [x] #771  
- [x] #772  
- [x] #773  
- [x] #774  
- [x] #775  
- [x] #776  
- [x] #777    

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Closed as have been supported.
